### ISSUE TITLE
Test failures with "make test"

### ISSUE THREAD

**Issue by eserte** [jozef/XML-Char#3]
If the distribution is built with `perl Makefile.PL`, then the test suite fails. Sample fail report on CPAN Testers: http://www.cpantesters.org/cpan/report/a453ee42-d485-11e9-95e0-d48c08e4b9a7

However, using `perl Build.PL` seems to be fine.

More links:
* overview of test reports: http://matrix.cpantesters.org/?dist=XML-Char+0.03
* statistical analysis also shows that failures happen only if `perl Makefile.PL` is used: http://analysis.cpantesters.org/solved?distv=XML-Char-0.03

**Comment by jozef** [comment]
Makefile.PL now removed from MANIFEST, 0.04 uploaded to CPAN
